// @vitest-environment jsdom
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import FormRenderer, { type RenderableFormField } from "@/components/forms/FormRenderer";
import ServiceCombobox from "@/components/ServiceCombobox";
import { applyOrgTheme } from "@/lib/theme/applyOrgTheme";
vi.mock("next/image", () => ({ default: ({ unoptimized, priority, ...props }: any) => <img {...props} /> }));
vi.mock("@/lib/supabaseClient", () => ({ supabase: { auth: { getSession: async () => ({ data: { session: { access_token: "token" } } }) } } }));
afterEach(cleanup);
const field = (type: RenderableFormField["type"], overrides = {}): RenderableFormField => ({ key: "answer", type, label: "Question", help_text: "Help", placeholder: "Answer", required: false, options: ["A","B"], width: "full", ...overrides });
describe("public form controls", () => {
  it.each(["short_text","long_text","email","phone","number","date","month_day","single_choice","multiple_choice","dropdown","yes_no"] as const)("renders the %s field with its label and help", type => { render(<FormRenderer title="Registration" fields={[field(type)]} />); expect(screen.getByText("Question")).toBeTruthy(); expect(screen.getByText("Help")).toBeTruthy(); expect(screen.getByRole("button", { name: "Submit" })).toBeTruthy(); });
  it("submits text and multiple selections with the honeypot", () => { const submit = vi.fn(); const { container } = render(<FormRenderer title="Registration" fields={[field("short_text"),field("multiple_choice",{key:"choices"})]} onSubmitAnswers={submit} />); fireEvent.change(screen.getByPlaceholderText("Answer"), { target: { value: "Alice" } }); fireEvent.click(screen.getByLabelText("A")); fireEvent.click(screen.getByLabelText("B")); fireEvent.submit(container.querySelector("form")!); expect(submit).toHaveBeenCalledWith({ answer: "Alice", choices: ["A","B"] }, ""); });
  it("retains read-only choice answers on submission", () => { const submit = vi.fn(); const { container } = render(<FormRenderer title="Update" fields={[field("dropdown")]} initialAnswers={{answer:"B"}} readOnlyFieldKeys={["answer"]} onSubmitAnswers={submit} />); fireEvent.submit(container.querySelector("form")!); expect(submit).toHaveBeenCalledWith({ answer: "B" }, ""); });
  it("never submits in preview mode", () => { const submit = vi.fn(); const { container } = render(<FormRenderer title="Preview" fields={[]} previewMode onSubmitAnswers={submit} />); fireEvent.submit(container.querySelector("form")!); expect(submit).not.toHaveBeenCalled(); expect((screen.getByRole("button") as HTMLButtonElement).disabled).toBe(true); });
  it("blocks submission when verification is pending", () => { render(<FormRenderer title="Registration" fields={[]} submitDisabled />); expect((screen.getByRole("button") as HTMLButtonElement).disabled).toBe(true); });
  it("clears an impossible day when changing birth month", () => { const { container } = render(<FormRenderer title="Birthday" fields={[field("month_day")]} initialAnswers={{answer:"01-31"}} />); fireEvent.change(screen.getByLabelText("Birth month"), {target:{value:"2"}}); expect((screen.getByLabelText("Birth day") as HTMLSelectElement).value).toBe(""); expect((container.querySelector('input[name="answer"]') as HTMLInputElement).value).toBe(""); });
  it("keeps leap-day birthday selection", () => { const submit = vi.fn(); const { container } = render(<FormRenderer title="Birthday" fields={[field("month_day")]} onSubmitAnswers={submit} />); fireEvent.change(screen.getByLabelText("Birth month"), { target:{value:"2"} }); fireEvent.change(screen.getByLabelText("Birth day"), { target:{value:"29"} }); fireEvent.submit(container.querySelector("form")!); expect(submit).toHaveBeenCalledWith({answer:"02-29"},""); });
});
describe("service picker interactions", () => {
  beforeEach(() => { vi.stubGlobal("confirm",vi.fn().mockReturnValue(true)); vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response(JSON.stringify({service:{id:"new",name:"Evening"}})))); });
  const services=[{id:"sun",name:"Sunday"},{id:"wed",name:"Wednesday"}];
  it("filters and selects an existing service", () => { const change=vi.fn(); render(<ServiceCombobox orgId="org" value="" services={services} onChange={change}/>); const input=screen.getByPlaceholderText(/Search services/); fireEvent.change(input,{target:{value:"wed"}}); expect(screen.queryByRole("button",{name:"Sunday"})).toBeNull(); fireEvent.click(screen.getByRole("button",{name:"Wednesday"})); expect(change).toHaveBeenCalledWith("wed"); });
  it("does not offer creation when disallowed", () => { render(<ServiceCombobox orgId="org" value="" services={services} onChange={vi.fn()} allowCreate={false}/>); fireEvent.change(screen.getByPlaceholderText(/Search services/),{target:{value:"New service"}}); expect(screen.queryByRole("button",{name:/Create/})).toBeNull(); });
  it("creates a service and selects the returned ID", async () => { const change=vi.fn(),created=vi.fn(); render(<ServiceCombobox orgId="org" value="" services={[]} onChange={change} onCreated={created}/>); fireEvent.change(screen.getByPlaceholderText(/Search services/),{target:{value:"Evening"}}); fireEvent.click(screen.getByRole("button",{name:/Create/})); await waitFor(()=>expect(change).toHaveBeenCalledWith("new")); expect(created).toHaveBeenCalledWith({id:"new",name:"Evening"}); expect(fetch).toHaveBeenCalledWith("/api/services",expect.objectContaining({headers:expect.objectContaining({"x-organization-id":"org"})})); });
  it("recovers from a network failure and permits retry", async () => { vi.mocked(fetch).mockRejectedValue(new Error("offline")); render(<ServiceCombobox orgId="org" value="" services={[]} onChange={vi.fn()}/>); fireEvent.change(screen.getByPlaceholderText(/Search services/),{target:{value:"Evening"}}); fireEvent.click(screen.getByRole("button",{name:/Create/})); await screen.findByText(/offline|Unable to create/); expect((screen.getByRole("button",{name:/Create/}) as HTMLButtonElement).disabled).toBe(false); });
});
describe("organization theme application", () => {
  it("updates supplied CSS variables", () => { applyOrgTheme({primary_rgb:"1 2 3",primary_hover_rgb:"4 5 6",accent_rgb:"7 8 9"}); expect(document.documentElement.style.getPropertyValue("--color-primary")).toBe("1 2 3"); expect(document.documentElement.style.getPropertyValue("--color-primary-hover")).toBe("4 5 6"); expect(document.documentElement.style.getPropertyValue("--color-accent")).toBe("7 8 9"); });
});
