import { beforeEach, describe, expect, it, vi } from "vitest";
import { database } from "./helpers/database";
const state=vi.hoisted(()=>({db:null as any,rpc:vi.fn()}));
vi.mock("@/lib/supabaseAdmin",()=>({supabaseAdmin:{from:(...args:any[])=>state.db.from(...args),rpc:state.rpc}}));
import { ensureEmailContact,resolveEmailEligibility,getEmailPreferenceContact,setEmailPreferences,consumePreferenceRateLimit } from "@/lib/server/email/repository";
import { ensureSmsSettings,getSmsState,saveSmsOnboarding,completeSmsOnboarding } from "@/lib/server/sms/repository";
const contact={id:"c",org_id:"org",member_id:"m",email_norm:"a@example.invalid"};
beforeEach(()=>{state.db=database();state.rpc.mockReset();state.rpc.mockResolvedValue({data:{ok:true},error:null});});
describe("email contacts and preferences",()=>{
 it("reuses an existing contact",async()=>{state.db.queue("email_contacts",{data:contact});expect(await ensureEmailContact("org"," A@EXAMPLE.INVALID ")).toEqual(contact);expect(state.db.calls.some((c:any)=>c.method==="insert")).toBe(false);});
 it("creates a normalized, tenant-scoped contact",async()=>{state.db.queue("email_contacts",{}, {data:contact});await ensureEmailContact("org"," A@EXAMPLE.INVALID ","m");expect(state.db.calls.find((c:any)=>c.method==="insert").args[0]).toMatchObject({org_id:"org",email_norm:"a@example.invalid",member_id:"m"});});
 it("updates the linked member when the contact already exists",async()=>{state.db.queue("email_contacts",{data:{...contact,member_id:null}},{data:contact});await ensureEmailContact("org","a@example.invalid","m");expect(state.db.calls.find((c:any)=>c.method==="update").args[0].member_id).toBe("m");});
 it.each([[true,false,"suppressed"],[false,true,"unsubscribed"],[false,false,"eligible"]])("suppression %s and opt-out %s yields %s",async(suppressed,optout,reason)=>{state.db.queue("email_contacts",{data:contact},{data:[{id:"c"}]});state.db.queue("email_global_suppressions",{data:suppressed?{id:"s"}:null});state.db.queue("email_topic_preferences",{data:optout?[{subscribed:false}]:[]});state.db.queue("organization_settings",{data:{mailing_address_line1:"123 Main",mailing_city:"City",mailing_state:"ST",mailing_postal_code:"12345",mailing_country:"US"}});const result=await resolveEmailEligibility("org","a@example.invalid","broadcast");expect(result.reason).toBe(reason);expect(result.mailingAddress).toContain("123 Main");});
 it("loads recipient preferences with defaults for unset topics",async()=>{state.db.queue("email_contacts",{data:{...contact,organizations:[{name:"Church"}]}});state.db.queue("email_topic_preferences",{data:[{topic:"broadcast",subscribed:false}]});const result=await getEmailPreferenceContact("c");expect(result?.organizationName).toBe("Church");expect(result?.preferences.broadcast).toBe(false);expect(result?.preferences.followup).toBe(true);});
 it("rejects an unknown contact before saving preferences",async()=>{await expect(setEmailPreferences({contactId:"missing",topics:["broadcast"],subscribed:false,source:"recipient"})).rejects.toThrow("unavailable");});
 it("records an opt-out and blocks pending followups",async()=>{state.db.queue("email_contacts",{data:contact},{data:contact});state.db.queue("email_topic_preferences",{data:[]},{},{data:[]});state.db.queue("members",{data:[{id:"m"}]});await setEmailPreferences({contactId:"c",topics:["followup","followup"],subscribed:false,source:"recipient"});const upsert=state.db.calls.find((c:any)=>c.method==="upsert");expect(upsert.args[0]).toHaveLength(1);expect(state.db.calls.find((c:any)=>c.table==="scheduled_followups"&&c.method==="update").args[0].status).toBe("blocked_preference");});
 it("rate-limits repeated preference requests",async()=>{state.db.queue("email_preference_rate_events",{count:30});await expect(consumePreferenceRateLimit("hash")).rejects.toThrow("Too many");expect(state.db.calls.some((c:any)=>c.method==="insert")).toBe(false);});
});
describe("SMS setup persistence",()=>{
 it("initializes without overwriting existing settings",async()=>{await ensureSmsSettings("org","actor");expect(state.db.calls.find((c:any)=>c.method==="upsert").args[1]).toMatchObject({ignoreDuplicates:true});});
 it("returns independent settings, draft, and attestation",async()=>{state.db.queue("sms_organization_settings",{data:{onboarding_status:"draft"}});state.db.queue("sms_onboarding_drafts",{data:{current_step:2}});expect(await getSmsState("org")).toEqual({settings:{onboarding_status:"draft"},onboarding:{current_step:2},attestation:null});});
 it("cannot overwrite tenant, actor, or provider status through a draft",async()=>{state.db.queue("sms_onboarding_drafts",{data:{current_step:2}});await saveSmsOnboarding("org","actor",{org_id:"other",updated_by:"attacker",onboarding_status:"approved",current_step:2});const row=state.db.calls.find((c:any)=>c.table==="sms_onboarding_drafts"&&c.method==="upsert").args[0];expect(row).toMatchObject({org_id:"org",updated_by:"actor",current_step:2});expect(row.onboarding_status).toBeUndefined();});
 it("rejects incomplete attestation",async()=>{state.rpc.mockResolvedValue({error:{message:"SMS_SETUP_INCOMPLETE"}});await expect(completeSmsOnboarding("org","actor","owner")).rejects.toThrow("Complete every required");});
 it("extracts the completed attestation from an RPC row array",async()=>{state.rpc.mockResolvedValue({data:[{id:"attestation"}],error:null});expect(await completeSmsOnboarding("org","actor","owner")).toEqual({id:"attestation"});expect(state.rpc.mock.calls[0][1]).toMatchObject({p_org_id:"org",p_actor_id:"actor",p_role:"owner"});});
});
