import LegalLayout from "./LegalLayout";
import { Toc, Section, P, Ul, Li, Divider } from "./LegalBlocks";

const TOC = [
  { id: "acceptance", label: "1. Acceptance of Terms" },
  { id: "service", label: "2. Description of Service" },
  { id: "eligibility", label: "3. Eligibility" },
  { id: "account", label: "4. Account Responsibilities" },
  { id: "plans", label: "5. Subscription Plans & Feature Limits" },
  { id: "payment", label: "6. Payment & Refund Policy" },
  { id: "data", label: "7. Data Ownership & Deletion" },
  { id: "children", label: "8. Children’s Data" },
  { id: "acceptable", label: "9. Acceptable Use" },
  { id: "warranty", label: "10. No Warranty" },
  { id: "liability", label: "11. Limitation of Liability" },
  { id: "indemnity", label: "12. Indemnification" },
  { id: "arbitration", label: "13. Arbitration & Dispute Resolution" },
  { id: "termination", label: "14. Termination" },
  { id: "changes", label: "15. Changes to Terms" },
  { id: "contact", label: "16. Contact" },
];

export default function TermsContent() {
  return (
    <LegalLayout
      title="Terms of Service"
      subtitle="Church Admin"
      meta={
        <div className="space-y-1">
          <div>
            <span className="font-medium">Effective Date:</span> [Insert Date]
          </div>
          <div>
            <span className="font-medium">Entity:</span> Davola Technologies, LLC (Tennessee Limited Liability Company)
          </div>
        </div>
      }
    >
      <Toc items={TOC} />

      <Section id="acceptance" title="1. Acceptance of Terms">
        <P>
          By accessing or using Church Admin (“Platform”), you agree to be bound by these Terms
          of Service (“Terms”).
        </P>
        <P>
          If you are using Church Admin on behalf of a church or organization, you represent
          that you have authority to bind that organization to these Terms.
        </P>
        <P>If you do not agree, do not use the Platform.</P>
      </Section>

      <Divider />

      <Section id="service" title="2. Description of Service">
        <P>
          Church Admin is a church administration and bookkeeping software platform designed to
          assist churches with:
        </P>
        <Ul>
          <Li>Member record management</Li>
          <Li>Attendance tracking</Li>
          <Li>Donation logging</Li>
          <Li>Financial reporting</Li>
          <Li>Internal communications</Li>
        </Ul>

        <P>Church Admin is not:</P>
        <Ul>
          <Li>A bank</Li>
          <Li>A payment processor</Li>
          <Li>An accounting firm</Li>
          <Li>A tax advisory service</Li>
          <Li>A legal advisor</Li>
        </Ul>

        <P>
          You are solely responsible for how you use financial data generated by the platform.
        </P>
      </Section>

      <Divider />

      <Section id="eligibility" title="3. Eligibility">
        <P>You must be at least 18 years old to create an account.</P>
        <P>
          The Platform may be accessed globally, but all services are operated from the United States.
        </P>
      </Section>

      <Divider />

      <Section id="account" title="4. Account Responsibilities">
        <P>You are responsible for:</P>
        <Ul>
          <Li>Maintaining account security</Li>
          <Li>Managing role-based permissions within your church</Li>
          <Li>Ensuring data entered is accurate</Li>
          <Li>Backing up any data you wish to preserve</Li>
        </Ul>
        <P>Church Admin is not responsible for data loss caused by user error.</P>
      </Section>

      <Divider />

      <Section id="plans" title="5. Subscription Plans & Feature Limits">
        <P>Church Admin operates on a tiered subscription model:</P>

        <P className="font-medium">Free Plan</P>
        <Ul>
          <Li>No Service Level Agreement (SLA)</Li>
          <Li>Feature limitations enforced automatically</Li>
          <Li>90-day data retention</Li>
          <Li>Usage caps on People records and emails</Li>
        </Ul>

        <P className="font-medium">Paid Plans (Basic, Pro, Enterprise)</P>
        <Ul>
          <Li>Feature access determined by active subscription</Li>
          <Li>Usage limits strictly enforced</Li>
          <Li>Data retention varies by tier</Li>
          <Li>Plan changes immediately adjust available features</Li>
        </Ul>

        <P>If usage exceeds plan limits:</P>
        <Ul>
          <Li>Access may be restricted</Li>
          <Li>Features may be temporarily disabled</Li>
          <Li>Upgrade may be required</Li>
        </Ul>

        <P>
          Church Admin reserves the right to modify plan features, limits, and pricing with reasonable notice.
        </P>
      </Section>

      <Divider />

      <Section id="payment" title="6. Payment & Refund Policy">
        <P>
          All subscription fees are billed in advance on a recurring monthly basis unless otherwise stated.
        </P>

        <P className="font-medium">7-Day Refund Window</P>
        <P>
          New paid subscriptions are eligible for a full refund if requested within 7 calendar days
          of the initial purchase.
        </P>

        <P>Refunds:</P>
        <Ul>
          <Li>Apply only to first-time subscription purchases</Li>
          <Li>Do not apply to renewals</Li>
          <Li>Do not apply after 7 days</Li>
        </Ul>

        <P>After the refund window expires, all payments are non-refundable.</P>
      </Section>

      <Divider />

      <Section id="data" title="7. Data Ownership & Deletion">
        <P>Churches retain ownership of the data entered into the platform.</P>

        <P>Upon cancellation:</P>
        <Ul>
          <Li>Data remains accessible for up to 30 days</Li>
          <Li>After 30 days, data may be permanently deleted</Li>
        </Ul>

        <P>You are responsible for exporting any data before deletion.</P>
        <P>
          Church Admin is not liable for data not exported before account termination.
        </P>
      </Section>

      <Divider />

      <Section id="children" title="8. Children’s Data">
        <P>Church Admin allows churches to store information about minors.</P>
        <P>The church is solely responsible for:</P>
        <Ul>
          <Li>Obtaining parental or guardian consent</Li>
          <Li>Compliance with COPPA or other child protection laws</Li>
        </Ul>
        <P>
          Church Admin acts as a service provider and does not independently collect data from minors.
        </P>
      </Section>

      <Divider />

      <Section id="acceptable" title="9. Acceptable Use">
        <P>You agree not to:</P>
        <Ul>
          <Li>Use the Platform for unlawful purposes</Li>
          <Li>Attempt unauthorized system access</Li>
          <Li>Reverse engineer the Platform</Li>
          <Li>Use the system to send spam or malicious content</Li>
          <Li>Interfere with service integrity</Li>
        </Ul>
        <P>We may suspend or terminate accounts violating these terms.</P>
      </Section>

      <Divider />

      <Section id="warranty" title="10. No Warranty">
        <P>The Platform is provided “as is” and “as available.”</P>
        <P>We make no guarantees regarding:</P>
        <Ul>
          <Li>Continuous availability</Li>
          <Li>Error-free performance</Li>
          <Li>Data recovery</Li>
          <Li>Fitness for a particular purpose</Li>
        </Ul>
        <P>Free plan users receive no uptime guarantees.</P>
      </Section>

      <Divider />

      <Section id="liability" title="11. Limitation of Liability">
        <P>To the maximum extent permitted by law:</P>
        <P>Church Admin shall not be liable for:</P>
        <Ul>
          <Li>Indirect damages</Li>
          <Li>Lost revenue</Li>
          <Li>Lost donations</Li>
          <Li>Data inaccuracies</Li>
          <Li>Compliance failures</Li>
          <Li>Tax reporting issues</Li>
        </Ul>
        <P>
          Total liability shall not exceed the amount paid to Church Admin in the 12 months preceding the claim.
        </P>
      </Section>

      <Divider />

      <Section id="indemnity" title="12. Indemnification">
        <P>
          You agree to indemnify and hold Church Admin harmless from claims arising from:
        </P>
        <Ul>
          <Li>Your misuse of the Platform</Li>
          <Li>Violation of these Terms</Li>
          <Li>Regulatory non-compliance</Li>
          <Li>Disputes within your church organization</Li>
        </Ul>
      </Section>

      <Divider />

      <Section id="arbitration" title="13. Arbitration & Dispute Resolution">
        <P className="font-medium">Mandatory Arbitration</P>
        <P>
          Any dispute arising from these Terms shall be resolved by binding arbitration in the State of Tennessee, conducted in accordance with the rules of the American Arbitration Association.
          under the rules of the American Arbitration Association.
        </P>

        <P className="font-medium">Class Action Waiver</P>
        <P>
          You agree that disputes may only be brought in your individual capacity and not as part of a class
          action or representative proceeding.
        </P>

        <P className="font-medium">Governing Law</P>
        <P>
          These Terms are governed by the laws of the State of Tennessee, without regard to conflict of law principles.
        </P>
      </Section>

      <Divider />

      <Section id="termination" title="14. Termination">
        <P>We may suspend or terminate accounts for:</P>
        <Ul>
          <Li>Non-payment</Li>
          <Li>Abuse</Li>
          <Li>Security risks</Li>
          <Li>Legal violations</Li>
        </Ul>
        <P>You may cancel your subscription at any time.</P>
      </Section>

      <Divider />

      <Section id="changes" title="15. Changes to Terms">
        <P>
          We may update these Terms from time to time. Continued use of the Platform constitutes acceptance
          of updated Terms.
        </P>
      </Section>

      <Divider />

      <Section id="contact" title="16. Contact">
        <P>
          Church Admin, LLC
          <br />
          [Insert Registered Business Address Once Formed]
          <br />
          [Insert Support Email]
        </P>
      </Section>
    </LegalLayout>
  );
}
