import { NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabaseAdmin";
import { apiStatus, directoryMembers, fetchAll, requirePeopleOperator } from "@/lib/server/people/directory";

const roles=new Set(["member","assistant_leader","leader"]); const clean=(v:unknown)=>typeof v==="string"?v.trim():"";

export async function GET(req:Request){try{const orgId=new URL(req.url).searchParams.get("org_id")??"";await requirePeopleOperator(req,orgId);const [departments,memberships,members]=await Promise.all([
 fetchAll<Record<string,unknown>>((f,t)=>supabaseAdmin.from("categories").select("id,name,status,created_at,updated_at").eq("org_id",orgId).eq("type","department").order("name").range(f,t)),
 fetchAll<Record<string,unknown>>((f,t)=>supabaseAdmin.from("member_departments").select("member_id,department_category_id,role,is_primary,status,joined_at,removed_at").eq("org_id",orgId).range(f,t)),directoryMembers(orgId)]);return NextResponse.json({departments,memberships,members});}catch(cause){const message=cause instanceof Error?cause.message:"Unable to load departments.";return NextResponse.json({error:message},{status:apiStatus(message)});}}

export async function POST(req:Request){try{const body=await req.json() as Record<string,unknown>;const orgId=clean(body.org_id);const {actorId}=await requirePeopleOperator(req,orgId);const action=clean(body.action);
 if(action==="save_department"){const name=clean(body.name);if(!name)throw new Error("Department name is required.");const id=clean(body.id);if(id){const {error}=await supabaseAdmin.from("categories").update({name,updated_at:new Date().toISOString()}).eq("id",id).eq("org_id",orgId).eq("type","department");if(error)throw new Error(error.message);}else{const {error}=await supabaseAdmin.from("categories").insert({org_id:orgId,name,type:"department",status:"active",created_by:actorId});if(error)throw new Error(error.message);}}
 else if(action==="set_department_status"){const id=clean(body.id),status=clean(body.status);if(!["active","archived"].includes(status))throw new Error("Invalid status.");if(status==="archived"){const {count}=await supabaseAdmin.from("member_departments").select("member_id",{count:"exact",head:true}).eq("department_category_id",id).eq("status","active");if((count??0)>0)throw new Error("Remove active workers before archiving this department.");}const {error}=await supabaseAdmin.from("categories").update({status,updated_at:new Date().toISOString()}).eq("id",id).eq("org_id",orgId).eq("type","department");if(error)throw new Error(error.message);}
 else if(action==="set_members"){const departmentId=clean(body.department_id),role=clean(body.role)||"member";if(!roles.has(role))throw new Error("Invalid role.");const ids=Array.isArray(body.member_ids)?body.member_ids.map(clean).filter(Boolean):[];if(!ids.length)throw new Error("Select at least one member.");const rows=ids.map(member_id=>({member_id,department_category_id:departmentId,org_id:orgId,role,is_primary:false,status:"active",removed_at:null,created_by:actorId,updated_by:actorId}));const {error}=await supabaseAdmin.from("member_departments").upsert(rows,{onConflict:"member_id,department_category_id"});if(error)throw new Error(error.message);}
 else if(action==="update_member"){const departmentId=clean(body.department_id),memberId=clean(body.member_id),role=clean(body.role),status=clean(body.status),primary=body.is_primary===true;if(!roles.has(role)||!["active","removed"].includes(status))throw new Error("Invalid membership.");if(primary&&status==="active")await supabaseAdmin.from("member_departments").update({is_primary:false}).eq("member_id",memberId).eq("org_id",orgId).eq("status","active");const {error}=await supabaseAdmin.from("member_departments").update({role,status,is_primary:status==="active"&&primary,removed_at:status==="removed"?new Date().toISOString():null,updated_by:actorId,updated_at:new Date().toISOString()}).eq("member_id",memberId).eq("department_category_id",departmentId).eq("org_id",orgId);if(error)throw new Error(error.message);const {data:active}=await supabaseAdmin.from("member_departments").select("department_category_id,is_primary").eq("member_id",memberId).eq("status","active").order("is_primary",{ascending:false}).limit(1);await supabaseAdmin.from("members").update({department_category_id:active?.[0]?.department_category_id??null,updated_by:actorId}).eq("id",memberId).eq("org_id",orgId);}
 else throw new Error("Invalid action.");return NextResponse.json({ok:true});}catch(cause){const message=cause instanceof Error?cause.message:"Unable to save department.";return NextResponse.json({error:message},{status:apiStatus(message)});}}
